"""inicial

Revision ID: 28c88ca4430a
Revises: 
Create Date: 2026-08-14 13:03:58.422958

"""
from alembic import op
import sqlalchemy as sa


revision = '28c88ca4430a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('fisica', 'juridica', name='tipopessoa'), nullable=False),
    sa.Column('status', sa.Enum('ativo', 'inativo', name='statuscliente'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('profissao', sa.String(), nullable=True),
    sa.Column('representante_legal_menor', sa.String(), nullable=True),
    sa.Column('razao_social', sa.String(), nullable=True),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('representante_legal', sa.String(), nullable=True),
    sa.Column('endereco_cep', sa.String(), nullable=False),
    sa.Column('endereco_logradouro', sa.String(), nullable=False),
    sa.Column('endereco_numero', sa.String(), nullable=False),
    sa.Column('endereco_complemento', sa.String(), nullable=True),
    sa.Column('endereco_bairro', sa.String(), nullable=False),
    sa.Column('endereco_cidade', sa.String(), nullable=False),
    sa.Column('endereco_uf', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('advogado', 'estagiario', 'cliente', name='role'), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('processos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('numero_processo', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('advogado_responsavel_id', sa.String(), nullable=False),
    sa.Column('area', sa.Enum('civel', 'trabalhista', 'tributario', 'penal', 'familia', 'empresarial', name='areadireito'), nullable=False),
    sa.Column('status', sa.Enum('ativo', 'suspenso', 'arquivado', 'encerrado', 'em_recurso', name='statusprocesso'), nullable=False),
    sa.Column('vara', sa.String(), nullable=False),
    sa.Column('comarca', sa.String(), nullable=False),
    sa.Column('valor_causa', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_abertura', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['advogado_responsavel_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processos_numero_processo'), 'processos', ['numero_processo'], unique=True)
    op.create_table('andamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('processo_id', sa.String(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('peticao', 'decisao', 'audiencia_marcada', 'movimentacao', 'sentenca', 'outro', name='tipoandamento'), nullable=False),
    sa.Column('autor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audiencias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('processo_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('conciliacao', 'instrucao', 'julgamento', 'una', name='tipoaudiencia'), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(), nullable=False),
    sa.Column('virtual', sa.Boolean(), nullable=False),
    sa.Column('link_video', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('agendada', 'realizada', 'cancelada', 'remarcada', name='statusaudiencia'), nullable=False),
    sa.Column('advogado_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['advogado_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('processo_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('peticao', 'contrato', 'procuracao', 'sentenca', 'comprovante', 'outro', name='tipodocumento'), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('versao_atual', sa.Integer(), nullable=False),
    sa.Column('upload_por', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faturas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('processo_id', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'paga', 'atrasada', 'cancelada', name='statusfatura'), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('pix', 'boleto', 'cartao', 'transferencia', name='formapagamento'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('partes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('processo_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('autor', 'reu', 'terceiro_interessado', name='tipoparte'), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prazos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('processo_id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('recurso', 'contestacao', 'manifestacao', 'audiencia', 'pagamento', 'outro', name='tipoprazo'), nullable=False),
    sa.Column('responsavel_id', sa.String(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_versoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('documento_id', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fatura_itens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fatura_id', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processo_documentos',
    sa.Column('processo_id', sa.String(), nullable=False),
    sa.Column('documento_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('processo_id', 'documento_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processo_documentos')
    op.drop_table('fatura_itens')
    op.drop_table('documento_versoes')
    op.drop_table('prazos')
    op.drop_table('partes')
    op.drop_table('faturas')
    op.drop_table('documentos')
    op.drop_table('audiencias')
    op.drop_table('andamentos')
    op.drop_index(op.f('ix_processos_numero_processo'), table_name='processos')
    op.drop_table('processos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('clientes')
    # ### end Alembic commands ###
