import { Usuario } from '../../models';

export const USUARIOS_SEED: Usuario[] = [
  {
    id: 'usr-1',
    nome: 'Marina Costa Alvarenga',
    email: 'marina.alvarenga@advocacia.com.br',
    senha: '123456',
    role: 'advogado',
    ativo: true,
  },
  {
    id: 'usr-2',
    nome: 'Rafael Nogueira Bittencourt',
    email: 'rafael.bittencourt@advocacia.com.br',
    senha: '123456',
    role: 'advogado',
    ativo: true,
  },
  {
    id: 'usr-3',
    nome: 'Juliana Prado Menezes',
    email: 'juliana.menezes@advocacia.com.br',
    senha: '123456',
    role: 'estagiario',
    ativo: true,
  },
  {
    id: 'usr-4',
    nome: 'Thiago Ramos Falcão',
    email: 'thiago.falcao@advocacia.com.br',
    senha: '123456',
    role: 'estagiario',
    ativo: true,
  },
  {
    id: 'usr-5',
    nome: 'Eduardo Martins Siqueira',
    email: 'eduardo.siqueira@cliente.com.br',
    senha: '123456',
    role: 'cliente',
    clienteId: 'cli-1',
    ativo: true,
  },
  {
    id: 'usr-6',
    nome: 'Helena Vasconcelos Tavares',
    email: 'helena.tavares@cliente.com.br',
    senha: '123456',
    role: 'cliente',
    clienteId: 'cli-2',
    ativo: true,
  },
  {
    id: 'usr-7',
    nome: 'Comercial Boa Vista Ltda',
    email: 'contato@boavista.com.br',
    senha: '123456',
    role: 'cliente',
    clienteId: 'cli-5',
    ativo: true,
  },
];
